
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module ex(

	//////////// CLOCK //////////
	input 		          		CLOCK_50,

	//////////// LED //////////
	output		     [7:0]		LED,

	//////////// KEY //////////
	input 		     [1:0]		KEY,

	//////////// SW //////////
	input 		     [3:0]		SW,

	//////////// ADC //////////
	output		          		ADC_CS_N,
	output		          		ADC_SADDR,
	output		          		ADC_SCLK,
	input 		          		ADC_SDAT,

	//////////// GPIO_0, GPIO_0 connect to Smart Car Daughtercard //////////
	output		          		BUZZER_OUT,
	output		          		IR_LED_ON,
	input 		          		IR_RXD,
	output		          		LED_LEFT,
	output		          		LED_RIGHT,
	output		          		LTC_ADC_CONVST,
	output		          		LTC_ADC_SCK,
	output		          		LTC_ADC_SDI,
	input 		          		LTC_ADC_SDO,
	output		          		MTRL_N,
	output		          		MTRL_P,
	output		          		MTRR_N,
	output		          		MTRR_P,
	
	input 		          		MTR_Fault_n,
	output		          		MTR_Sleep_n,
	inout 		     [7:0]		TMD0,
	inout 		     [7:0]		TMD1,
	output		          		VCC3P3_PWRON_n
);

//=======================================================
//  REG/WIRE declarations
//=======================================================
 wire       HZ_655 ; 
 wire       ALARM_LED ;  
 wire [7:0] LED_M ; 
 wire       Outlet  ; 
 wire       TRACK_IR;
 wire       TRACK_MUN;
 wire       TRACK_DEMO;
 wire       TRACK ;
 wire       PLAY_IR;
 wire       PLAY_MUN;
 wire       PLAY_DEMO;
 wire       PLAY ;
 wire       START_IR;
 wire       TURN_R_IR; 
 wire       TURN_L_IR; 
 wire       FD_BK;
 wire [15:0]ADC_CN ; 
 wire [15:0]ADC_L0,ADC_L1,ADC_L2 ; 
 wire [15:0]ADC_R0,ADC_R1,ADC_R2; 
 wire       ON_OFF;
 wire       L,R,C;
 wire [7:0] BLINK_L ; 
 wire       HZ_50M  ;
 
 wire       LED_T;   

 wire       MOTOR_L_D; 
 wire       MOTOR_R_D;  
 wire       FORD_D ; 

 wire       OFF_IR ;
 wire       PLAY_BB ;
 wire       PLAY_WH ;
 wire       WH_FB;

 // RF remote control wires
 wire [7:0] uart_data;
 wire       uart_valid;
 wire       rf_track, rf_start, rf_turn_r, rf_turn_l;
 wire       rf_manu_t, rf_return, rf_fd_bk;
//=======================================================
//  Structural coding
//=======================================================

//--- SCD MOTOR SLEEP DISABLE ----
assign MTR_Sleep_n    = 1;
assign IR_LED_ON      = 1;
assign VCC3P3_PWRON_n = 0;

//--- UART RX from STM32 (via TMD1[7]) ---
UART_RX  urx(
   .CLK     ( CLOCK_50  ),
   .RESET_N ( KEY[0]    ),
   .RXD     ( TMD1[7]   ),
   .DATA    ( uart_data  ),
   .VALID   ( uart_valid )
);

//--- RF Command Decoder ---
RF_CMD_DEC  rfd(
   .CLK       ( CLOCK_50  ),
   .RESET_N   ( KEY[0]    ),
   .DATA      ( uart_data  ),
   .VALID     ( uart_valid ),
   .TRACK     ( rf_track   ),
   .START     ( rf_start   ),
   .TURN_R    ( rf_turn_r  ),
   .TURN_L    ( rf_turn_l  ),
   .MANU_T    ( rf_manu_t  ),
   .RF_RETURN ( rf_return  ),
   .FD_BK     ( rf_fd_bk  )
);
//--- SCD 8CH ADC OUTPUT ---- 
ADC_CH_OUT  v( 
   .CLK_50     ( CLOCK_50),		      
   .RESET_N    ( KEY[0]  ) ,	
   .ADC_CONVST ( LTC_ADC_CONVST), 
   .ADC_DIN    ( LTC_ADC_SDI   ),
   .ADC_DOUT   ( LTC_ADC_SDO   ),
   .ADC_SCLK   ( LTC_ADC_SCK   ),
   .CD0	      ( ADC_R2),
   .CD1	      ( ADC_R1),
   .CD2	      ( ADC_R0),		
   .CD3	      ( ADC_CN),
   .CD4	      ( ADC_L0),
   .CD5	      ( ADC_L1),
   .CD6	      ( ADC_L2),
   .CD7	      ( ),
   .SW         ( 4'b0110 ) ,
   .LED        ( LED_M)   //  0~16V / 8  ; 	R1/( R1+R2 )  = 1/4 
);

//---------------------------------------------------------------------
//-- Trace_Car & Line_Sensor & Motor Processing --
TRACE_SENSOR_MOTOR  tr( 
 .ADC_CS_N ( LTC_ADC_CONVST ) , 
 .CLK      ( CLOCK_50 ) ,
 .RESET_N  ( 1) ,
 .TR_ON_OFF( 1'b1),
//LRC OUT
 .L        ( L),
 .R        ( R),
 .C        ( C),  	 
//--ANALOG SENSOR 
 .ADC_CN   ( ADC_CN) ,
 .ADC_L0   ( ADC_L0) , 
 .ADC_R0   ( ADC_R0) ,
 .ADC_L1   ( ADC_L1) , 
 .ADC_R1   ( ADC_R1) , 
 .ADC_L2   ( ADC_L2) , 
 .ADC_R2   ( ADC_R2) ,    
 .M0B      ( MTRL_P),// L_MOTOR
 .M0A      ( MTRL_N),// L_MOTOR
 .M1B      ( MTRR_N),// R_MOTOR  
 .M1A      ( MTRR_P),// R_MOTOR  
//--RF remote command
 .TRACK    ( rf_track  ),
 .START    ( rf_start  ),
 .RETURN   ( rf_return ),
 .TURN_R   ( rf_turn_r ),
 .TURN_L   ( rf_turn_l ),
 .MANU_T   ( rf_manu_t ),
 .FD_BK    ( rf_fd_bk  ),
 .Outlet   ( Outlet) 
);

endmodule
